#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\ConferenceController::index

conference:
    path: /conference/{slug}
    controller: App\Controller\ConferenceController::show

conference_header:
    path: /conference_header
    controller: App\Controller\ConferenceController::conferenceHeader

admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

review_comment:
    path: /admin/comment/review/{id}
    controller: App\Controller\AdminController::reviewComment
